language: php
sudo: false

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: COVERAGE=run
  allow_failures:
    - php: 7.2
  fast_finish: true

install:
  - composer self-update
  # install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  #- phpenv config-rm xdebug.ini
  # install packages
  - composer install --no-interaction
  - if [[ $COVERAGE = run ]]; then mkdir -p build/logs; PHPUNIT_FLAGS="--coverage-text --coverage-clover build/logs/clover.xml"; fi

script:
  # run PHPUnit and export code coverage log
  - if [[ $COVERAGE = run ]]; then phpunit -c ./ $PHPUNIT_FLAGS; fi

after_success:
  # build phar
  - composer box
  # submit coverage report to Coveralls
  - if [[ $COVERAGE = run ]]; then travis_retry php coveralls.phar -v; fi
  # submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # deploy docs to website
  - provider: script
    script: bash scripts/deploy-docs.sh
    skip_cleanup: true
    overwrite: true
    on:
      branch: master
      php: '7.1'
  # deploy to GitHub release
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "dist/cecil.phar"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      php: '7.1'
  # deploy dist file to website
  - provider: script
    script: bash scripts/deploy-dist.sh
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      php: '7.1'
