language: php
php:
  - 5.6
  - 7.0
# faster builds on new travis setup not using sudo
sudo: false
# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
# update composer it-self
install:
  - composer self-update
# install package
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - mkdir -p build/logs
# run PHPUnit and export code coverage log
script:
  - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
# deploy docs to website
after_success:
  - bash deploy-docs.sh
# build phar
before_deploy: vendor/bin/box build
# deploy
deploy:
  # deploy to GitHub release
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "dist/phpoole.phar"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      php: '7.0'
  # deploy dist file to website
  - provider: script
    script: deploy-dist.sh
    skip_cleanup: true
    overwrite: true
    on:
      #tags: true
      branch: dist
      php: '7.0'
