language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $COMPOSER_CACHE_DIR

php:
  - 7.1
  - 7.2

stages:
  - test
  - code coverage
  - deploy release
  - deploy docs

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE != true ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install -n --prefer-source
  - if [[ $TEST_COVERAGE == true ]]; then travis_retry composer test-coverage-install || return 0 ; fi

script: composer test

jobs:
  allow_failures:
    - php: 7.2
    - stage: code coverage
  include:
    - stage: code coverage
      php: 7.1
      if: (NOT type IN (pull_request)) AND (branch = master)
      env:
        - TEST_COVERAGE=true
      before_script:
        - mkdir -p build/logs
      script:
        - travis_retry composer test-coverage
      after_success:
        - travis_retry composer test-coverage-upload
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      php: "7.1"
      if: tag IS present
      script: composer box
      deploy:
        # GitHub release
        - provider: releases
          api_key: $GH_TOKEN
          file: "dist/cecil.phar"
          skip_cleanup: true
          overwrite: true
          on:
            branch: master
            tags: true
        # dist files
        - provider: script
          script: bash scripts/deploy-dist.sh
          skip_cleanup: true
          overwrite: true
          on:
            branch: master
            tags: true
    - stage: deploy docs
      php: "7.1"
      if: (NOT type IN (pull_request)) AND (branch = master)
      install: skip
      script: skip
      deploy:
        - provider: script
          script: bash scripts/deploy-docs.sh
          skip_cleanup: true
          overwrite: true
          on:
            branch: master
